config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  # get 'posts/index' => 'posts#index'
  #
  # get 'posts/create' => 'posts#create'
  #
  # get 'posts/edit' => 'posts#edit'

  resources :posts

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get 'users/new' => 'users#new'

  get 'users/create' => 'users#create'

  get '/new_account' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_permalink

  belongs_to :user

  has_many :tag_sets
  has_many :tags, through: :tag_sets

  scope :sorted, -> { order(:updated_at => :desc) }
  scope :search_by_title, ->(query) { where(['title LIKE ?', "%#{query}"]) }
  scope :search_by_user, ->(query) { where(['user_id LIKE ?', "%#{query}"]) }

  validates :title, :presence => true, :length => {within: 1..255}
  validates :content, :presence => true, :length => {minimum: 10}

  # Setter
  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end

  # Getter
  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def self.get_username(id)
    User.find(id).username
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_permalink :name

  has_many :tag_sets
  has_many :posts, through: :tag_sets

  scope :search_by_name, -> (query) { where(['name LIKE ?', "%#{query}"]) }
  scope :sorted, -> { order(:name => :asc) }

  validates :name, presence: true, length: {within: 1..255}, uniqueness: true

end

app/models/tag_set.rb
class TagSet < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_permalink :username
  has_secure_password

  has_many :posts
  has_many :tags, through: :posts

  scope :sorted, -> { order(:username => :asc) }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: true, length: {within: 8..25}
  validates :email, presence: true, format: EMAIL_REGEX
  validates :password, presence: true, length: {minimum: 8}, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  # TODO: Add this method to all necessary controllers via before_action
  def authorize
    redirect_to('/login') unless @current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :current_user

  # before_action :authorize

  def index
    @posts = Post.sorted
  end

  def show
    @post = Post.find_by_permalink(params[:id])
  end

  def new
    logger.debug('Called "new" action')
    @post = Post.new
  end

  def create
    logger.debug('Called "create" action')
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Your post is now published!'
      redirect_to(posts_path)
    else
      logger.debug(@post.errors.full_messages)
      redirect_to(new_post_path)
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = 'Your post has been updated!'
      redirect_to(posts_path(@post))
    else
      render('edit')
    end
  end

  private

  def post_params
    # params.require(:post).permit(:user_id, :content, :all_tags)
    params.require(:post).permit(:title, :content, :user_id)
    # params['post']['all_tags'] = params['post']['all_tags'].split(',').strip('"')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    logger.debug(params[:password])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render('new')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to('/')
    else
      render('new')
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_error_messages.erb
<% if object && object.errors.size > 0 %>
    <div class="ui error message">
      <div class="header">
        <%= pluralize(object.errors.size, 'error') %> with your submission
      </div>
      <ul class="list">
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Empathy Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="ui stackable container top fixed teal inverted menu">
  <div class="container">
    <!--<div class="header item">The Empathy Project</div>-->
    <%= link_to('The Empathy Project', root_path, :class => 'header item') %>
    <%= link_to('New Post', new_post_path, html_options = {:class => 'item'}) %>
    <% if current_user != nil %>
        <%= link_to('Log Out', {:controller => 'sessions', :action => 'destroy'}, html_options = {:class => 'item'}) %>
    <% else %>
        <%= link_to('Login', {:controller => 'sessions', :action => 'new'}, html_options = {:class => 'item'}) %>
    <% end %>
  </div>
</div>

<div class="ui very relaxed divided items very padded container segment">

  <% @posts.each do |post| %>
      <!--<div class="item">-->
      <div class="ui raised very padded text container segment">
        <div class="content">
          <div class="ui header"><%= post.title %></div>
          <h5 class="meta"><%= Post.get_username(post.user_id) %></h5>
          <div class="description">
            <p><%= post.content %></p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="new post">
  <div class="ui middle aligned center aligned grid">
    <div class="three column">
      <h2 class="ui header teal">
        <div class="content">New Post</div>
      </h2>
      <%= form_for @post, url: posts_url, :html => {:class => 'ui large form'} do |f| %>
          <div class="ui stacked segment">
            <div class="required field">
              <%= f.text_field :title, placeholder: 'Title' %>
            </div>
            <!--<div class="hidden field">-->
            <%= f.hidden_field :user_id, value: current_user.id %>
            <!--</div>-->
            <div class="required field">
              <%= f.text_area(:content, placeholder: 'Share your story! (Minimum 10 characters)') %>
            </div>
            <!--<div class="ui fluid multiple search selection dropdown">-->
            <!--<%# f.hidden_field :all_tags %>-->
            <!--<i class="dropdown icon"></i>-->
            <!--<div class="menu">-->
            <!--<%# Tag.sorted.each do |tag| %>-->
            <!--<div class="item" data-value=<%# tag.name.to_s %>>-->
            <!--<%# tag.name.to_s %>-->
            <!--</div>-->
            <!--<%# end %>-->

            <%# f.collection_select :all_tags,
                                    Tag.sorted,
                                    :name,
                                    :name,
                                    {},
                                    {class: 'ui multiple search selection dropdown',
                                     id: 'multi-select',
                                     multiple: '',
                                    } %>
            <%= f.submit('Post', :class => 'ui fluid large teal submit button') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<footer>
  <% javascript_include_tag :posts %>
</footer>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<!-- TODO: Extract surrounding logic for partial -->
<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal header">
      <div class="content">
        Create New Account
      </div>
    </h2>
    <%= form_for :user, url: '/users', :html => {:class => 'ui large form'} do |f| %>
        <div class="ui stacked segment">
          <div class="required field">
            <%= f.text_field(:username, :placeholder => 'username') %>
          </div>
          <div class="field">
            <%= f.text_field(:email, :placeholder => 'email address') %>
          </div>
          <div class="two fields">
            <div class="required field">
              <%= f.password_field(:password, :placeholder => 'password') %>
            </div>
            <div class="required field">
              <%= f.password_field(:password_confirmation, :placeholder => 'confirm password') %>
            </div>
          </div>
          <%= f.submit('Submit', :class => 'ui fluid teal submit button') %>
        </div>

    <% end %>
    <% if @user.errors.any? %>
        <div class="bottom attached">
          <%= error_messages_for(@user) %>
        </div>
    <% end %>
  </div>



</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>The Empathy Project</title>

  <style type="text/css">
    a {
      color: snow;
    }

    .hidden.menu {
      display: none;
    }

    .masthead {
      background-color: #36D7B7 !important;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }

    .masthead .logo.item img {
      margin-right: 1em;
    }

    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }

    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0;
      font-size: 4em;
      font-weight: normal;
    }

    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0;
    }

    .ui.vertical.stripe h3 {
      font-size: 2em;
    }

    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }

    .ui.vertical.stripe .floated.image {
      clear: both;
    }

    .ui.vertical.stripe p {
      font-size: 1.33em;
    }

    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0;
    }

    .quote.stripe.segment {
      padding: 0;
    }

    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }

      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }

      .secondary.pointing.menu .toc.item {
        display: block;
      }

      .masthead.segment {
        min-height: 350px;
      }

      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }

      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


  </style>
  <script>
      $(document)
          .ready(function () {

              // fix menu when passed
              $('.masthead')
                  .visibility({
                      once: false,
                      onBottomPassed: function () {
                          $('.fixed.menu').transition('fade in');
                      },
                      onBottomPassedReverse: function () {
                          $('.fixed.menu').transition('fade out');
                      }
                  })
              ;

              // create sidebar and attach to menu open
              $('.ui.sidebar')
                  .sidebar('attach events', '.toc.item')
              ;

          })
      ;
  </script>
</head>
<body>

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="item">The Empathy Project</a>
    <div class="right menu">
      <div class="item">
        <%= link_to('Log In', {:controller => 'sessions', :action => 'new'}, :class => 'ui button') %>
      </div>
      <div class="item">
        <%= link_to('Sign Up', {:controller => 'users', :action => 'new'}, :class => 'ui teal button') %>
      </div>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <%= link_to('Log In', {:controller => 'sessions', :action => 'new'}, :class => 'ui button') %>
  <%= link_to('Sign Up', {:controller => 'users', :action => 'new'}, :class => 'ui teal button') %>
</div>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <div class="right item">
          <%= link_to('Log In', {:controller => 'sessions', :action => 'new'}, :class => 'ui inverted button') %>
          <%= link_to('Sign Up', {:controller => 'users', :action => 'new'}, :class => 'ui inverted button') %>
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        The Empathy Project
      </h1>
      <h2>Building bridges one story at a time</h2>
      <!--<div class="ui black huge button">-->
      <%= link_to('Let\'s Go', posts_path, :class => 'ui black huge button') %>
      <!--</div>-->
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <p>The Empathy Project is a new type of social network entirely focused on sharing stories about uncomfortable
        topics. This is a community for people who want to learn about other people from their own perspective. Sound interesting?
        Click the link at the top to sign up!
      </p>

    </div>
  </div>
  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>Future Features</h3>
          <ul class="ui left aligned list">
            <li>Tagged Posts</li>
            <li>Follow Users</li>
            <li>Search</li>
            <li>And more!</li>
          </ul>
        </div>
        <div class="column">
          <h3>"Empathy is the most mysterious transaction that the human soul can have, and it's accessible to all of us, but we have to give ourselves the opportunity to identify, to plunge ourselves in a story where we see the world from the bottom up or through another's eyes or heart."</h3>
          <p>
            <i class="user icon"></i> <b>Sue Monk Kidd</b>
          </p>
        </div>
        <div class="column">
          <h3>"I believe that stories are incredibly important, possibly in ways we don't understand, in allowing us to make sense of our lives, in allowing us to escape our lives, in giving us empathy and in creating the world that we live in."</h3>
          <p>
            <i class="user icon"></i> <b>Neil Gaiman</b>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>


</body>

</html>